---

- name: Show vm settings
  ansible.builtin.debug:
    msg:
      name: "{{ vm_name }}"
      guest_id: "{{ vm_settings['guest_id'] }}"
      folder: "{{ vm_folder }}"

- name: Create VM
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    port: "{{ vcenter_port | default(omit) }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    proxy_host: "{{ vcenter_proxy_host | default(omit) }}"
    proxy_port: "{{ vcenter_proxy_port | default(omit) }}"

    datacenter: "{{ vm_datacenter }}"
    cluster: "{{ vm_cluster }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    state: present
    guest_id: "{{ vm_settings['guest_id'] }}"
    disk: "{{ vm_settings['disk'] }}"
    cdrom: "{{ vm_settings['cdrom'] }}"
    hardware: "{{ vm_settings['hardware'] }}"
    networks: "{{ vm_settings['networks'] }}"
