---

- name: Include tasks from vm-poweroff.yml
  ansible.builtin.include_tasks: vm-poweroff.yml

- name: Delete VM
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    port: "{{ vcenter_port | default(omit) }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    proxy_host: "{{ vcenter_proxy_host | default(omit) }}"
    proxy_port: "{{ vcenter_proxy_port | default(omit) }}"
    datacenter: "{{ vm_datacenter }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    state: absent
