---

- name: Deploy VM from template
  throttle: "{{ vmware_parallel_deployments }}"
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    port: "{{ vcenter_port | default(omit) }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    proxy_host: "{{ vcenter_proxy_host | default(omit) }}"
    proxy_port: "{{ vcenter_proxy_port | default(omit) }}"

    datacenter: "{{ vm_datacenter | default(omit) }}"
    cluster: "{{ vm_cluster if vm_host is undefined else omit }}"
    esxi_hostname: "{{ vm_host | default(omit) }}"
    name: "{{ vm_name }}"
    folder: "{{ vm_folder }}"
    template: "{{ vm_template }}"

    cdrom: []
    customization:
      dns_servers: "{{ vm_dns_servers | default(omit) }}"
      dns_suffix: "{{ vm_dns_suffix | default(omit) }}"
      domain: "{{ vm_domain | default(omit) }}"
      existing_vm: "{{ vm_customization | default(False) }}"
      hostname: "{{ vm_hostname | default(omit) }}"
    datastore: "{{ vm_settings['datastore'] | default(omit) }}"
    disk: "{{ vm_settings['disk'] | default(omit) }}"
    hardware: "{{ vmware_vm_settings['hardware'] | combine(vm_settings['hardware'], recursive=true) }}"
    networks: "{{ vm_settings['networks'] }}"

- name: Wait for 15 seconds
  ansible.builtin.pause:
    seconds: 15

- name: Reconfigure disk / networking / customization
  throttle: "{{ vmware_parallel_deployments }}"
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    port: "{{ vcenter_port | default(omit) }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    proxy_host: "{{ vcenter_proxy_host | default(omit) }}"
    proxy_port: "{{ vcenter_proxy_port | default(omit) }}"

    datacenter: "{{ vm_datacenter | default(omit) }}"
    cluster: "{{ vm_cluster if vm_host is undefined else omit }}"
    esxi_hostname: "{{ vm_host | default(omit) }}"
    name: "{{ vm_name }}"
    folder: "{{ vm_folder }}"

    customization:
      dns_servers: "{{ vm_dns_servers | default(omit) }}"
      dns_suffix: "{{ vm_dns_suffix | default(omit) }}"
      domain: "{{ vm_domain | default(omit) }}"
      existing_vm: "{{ vm_customization | default(False) }}"
      hostname: "{{ vm_hostname | default(omit) }}"
    networks: "{{ vm_settings['networks'] }}"

- name: Add vGPU profile to VM
  throttle: "{{ vmware_parallel_deployments }}"
  community.vmware.vmware_guest_vgpu:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vm_datacenter | default(omit) }}"
    validate_certs: false
    name: "{{ vm_name }}"
    vgpu: "{{ vm_settings['vgpu'] }}"
    state: present
  when: vm_settings['vgpu'] | default('') | length > 0
