---

- name: Check for VM
  community.vmware.vmware_guest_info:
    hostname: "{{ vcenter_hostname }}"
    port: "{{ vcenter_port | default(omit) }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    proxy_host: "{{ vcenter_proxy_host | default(omit) }}"
    proxy_port: "{{ vcenter_proxy_port | default(omit) }}"
    datacenter: "{{ vm_datacenter | default(omit) }}"
    name: "{{ vm_name }}"
  failed_when: false
  register: vm_status

- name: Poweroff VM
  when: vm_status.instance.moid is defined
  block:

    - name: Power-off VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        port: "{{ vcenter_port | default(omit) }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        proxy_host: "{{ vcenter_proxy_host | default(omit) }}"
        proxy_port: "{{ vcenter_proxy_port | default(omit) }}"

        datacenter: "{{ vm_datacenter | default(omit) }}"
        name: "{{ vm_name }}"
        state: "{{ vm_shutdown_mode | default('poweredoff') }}"

    - name: Wait for VM to be poweredoff
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        port: "{{ vcenter_port | default(omit) }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        proxy_host: "{{ vcenter_proxy_host | default(omit) }}"
        proxy_port: "{{ vcenter_proxy_port | default(omit) }}"

        datacenter: "{{ vm_datacenter | default(omit) }}"
        name: "{{ vm_name }}"

      register: vm_status
      until: vm_status.instance.hw_power_status == "poweredOff"
      retries: 180
      delay: 10
