---

- name: centos7
  ci: false
  box: cloud-image/centos-7
- name: centos8
  ci: false
  box: cloud-image/centos-8
- name: centos8s
  ci: false
  box: cloud-image/centos-8-stream
- name: centos9s
  ci: false
  box: cloud-image/centos-9-stream
- name: centos10s
  ci: false
  box: cloud-image/centos-10-stream
- name: rockylinux8
  ci: true
  box: cloud-image/rocky-8
- name: rockylinux9
  ci: true
  box: cloud-image/rocky-9
- name: rockylinux10
  ci: true
  box: cloud-image/rocky-10
- name: oraclelinux8
  ci: true
  box: cloud-image/oracle-linux-8
- name: oraclelinux9
  ci: true
  box: cloud-image/oracle-linux-9
- name: oraclelinux10
  ci: true
  box: cloud-image/oracle-linux-10
- name: olam8
  ci: false
- name: almalinux8
  ci: true
  box: cloud-image/almalinux-8
- name: almalinux9
  ci: true
  box: cloud-image/almalinux-9
- name: almalinux10
  ci: true
  box: cloud-image/almalinux-10
- name: opensuse15
  ci: false
  box: generic/opensuse15
- name: opensuse16
  ci: false
  box: generic/opensuse16
- name: debian10
  ci: false
  box: cloud-image/debian-10
- name: debian11
  ci: true
  box: cloud-image/debian-11
- name: debian12
  ci: true
  box: cloud-image/debian-12
- name: debian13
  ci: true
  box: cloud-image/debian-13
- name: ubuntu1804
  ci: false
  box: cloud-image/ubuntu-18.04
- name: ubuntu2004
  ci: true
  box: cloud-image/ubuntu-20.04
- name: ubuntu2204
  ci: true
  box: cloud-image/ubuntu-22.04
- name: ubuntu2404
  ci: true
  box: cloud-image/ubuntu-24.04
- name: ubuntu2604
  ci: true
  box: cloud-image/ubuntu-26.04
- name: fedora37
  ci: false
  box: generic/fedora37
- name: fedora38
  ci: false
  box: cloud-image/fedora-38
- name: fedora39
  ci: false
  box: cloud-image/fedora-39
- name: fedora40
  ci: false
  box: cloud-image/fedora-40
- name: fedora41
  ci: false
  box: cloud-image/fedora-41
- name: fedora42
  ci: false
  box: cloud-image/fedora-42
- name: fedora43
  ci: true
  box: cloud-image/fedora-43
- name: fedora44
  ci: false
  box: cloud-image/fedora-44
- name: alpine3
  ci: false
  box: cloud-image/alpine-3.24
- name: win2012r2
  ci: false
  box: jborean93/WindowsServer2012R2
  groups: ['windows']
- name: win2016
  ci: false
  box: jborean93/WindowsServer2016
  groups: ['windows']
- name: win2019
  ci: false
  box: jborean93/WindowsServer2019
  groups: ['windows']
- name: win2022
  ci: false
  box: jborean93/WindowsServer2022
  groups: ['windows']
- name: win2025
  ci: false
  box: jborean93/WindowsServer2025
  groups: ['windows']
